### PR TITLE
DiscordTournamentBot createTeam command

### PR DESCRIPTION
**Pull request by dartrix**
Added CreateTeam command

### CODE REVIEW

**Comment by Nebri** [comment]
@dartrix first thing I notice is that your making a pull request into our master branch when this should have gone into the Development branch. Are you able to select our development as the pull request target?

**Comment by Nebri** [comment]
@kupych when you are able to, can you please run through this pull request and do a code review?

**Comment by kupych** [comment]
A couple things:

1 - Instead of trying to parse the playerLimit and expecting an error, I would check with TryParse first, so you could do something like this: 
```
int playerLimit;    
    if (!int.TryParse(playerlimit, out n)) throw new ArgumentException("Player limit is not a valid number");
    if (playerLimit < 1) throw new ArgumentException("Player limit is not a valid number");`
```
and so on.

2 - The check for the correct number of arguments in the switch case is redundant - you're already checking for all the other errors in the CreateTeamCommand class, and your try-catch loop in the constructor will also catch an improper number of arguments. If you try to get args[4] from a List with length 3, it will throw an "ArgumentOutOfRangeException" which you are catching anyway. You can handle it in the catch as follows:

```
try {...}
catch (ArgumentOutOfRangeException ex) {
    response = "Invalid number of arguments";
}

catch (Exception ex) {
    // general exception handling here
}
```

Other than that stuff I think it looks good!

**Comment by Nebri** [comment]
@kupych that's a great write up, the only thing I'd like to add is that a player limit of zero should infer that the team has no player limit. so use: 

`if (playerLimit < 0) throw new ArgumentException("Player limit is not a valid number");``

instead :).

**Pull request closed without merging**
